// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoanApp.Migrations
{
    [DbContext(typeof(FinansDbContext))]
    [Migration("20260407130848_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KrediHesap", b =>
                {
                    b.Property<int>("KrediId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KrediId"));

                    b.Property<decimal>("AnaPara")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DovizCinsi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FaizOrani")
                        .HasColumnType("numeric");

                    b.Property<decimal>("KalanBorc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KrediTuru")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MusteriId")
                        .HasColumnType("integer");

                    b.Property<string>("OdemeTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ToplamBorc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VadeSayisi")
                        .HasColumnType("integer");

                    b.HasKey("KrediId");

                    b.HasIndex("MusteriId");

                    b.ToTable("Krediler");
                });

            modelBuilder.Entity("Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KullaniciId"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("KullaniciId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("MevduatHesap", b =>
                {
                    b.Property<int>("HesapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HesapId"));

                    b.Property<decimal>("Bakiye")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DovizCinsi")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("IbanNo")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("integer");

                    b.HasKey("HesapId");

                    b.HasIndex("MusteriId");

                    b.ToTable("MevduatHesaplari");
                });

            modelBuilder.Entity("Musteri", b =>
                {
                    b.Property<int>("MusteriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MusteriId"));

                    b.Property<string>("Sektor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("VKN")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("MusteriId");

                    b.HasIndex("VKN")
                        .IsUnique();

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("Tahsilat", b =>
                {
                    b.Property<int>("TahsilatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TahsilatId"));

                    b.Property<int>("HesapId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KrediId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TahsilatTutari")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TahsilatId");

                    b.HasIndex("HesapId");

                    b.HasIndex("KrediId");

                    b.ToTable("Tahsilatlar");
                });

            modelBuilder.Entity("KrediHesap", b =>
                {
                    b.HasOne("Musteri", "Musteri")
                        .WithMany("Krediler")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("MevduatHesap", b =>
                {
                    b.HasOne("Musteri", "Musteri")
                        .WithMany("MevduatHesaplari")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("Tahsilat", b =>
                {
                    b.HasOne("MevduatHesap", "Hesap")
                        .WithMany()
                        .HasForeignKey("HesapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KrediHesap", "Kredi")
                        .WithMany()
                        .HasForeignKey("KrediId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hesap");

                    b.Navigation("Kredi");
                });

            modelBuilder.Entity("Musteri", b =>
                {
                    b.Navigation("Krediler");

                    b.Navigation("MevduatHesaplari");
                });
#pragma warning restore 612, 618
        }
    }
}
